---
version: 2.1

jobs:
  lint_with_node:
    docker:
      - image: circleci/node:12.19.0
    working_directory: ~/app_lintwithnode
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ .Environment.CACHE_VERSION }}-lint_with_node

      - run:
          name: npm module install
          command: |
            make setup_node_module

      - save_cache:
          key: cache-{{ .Environment.CACHE_VERSION }}-lint_with_node
          paths:
            - ./node_modules

      - run:
          name: markdownlint
          command: |
            make lint_markdown

  file_check:
    docker:
      - image: circleci/python:3.8.6
    working_directory: ~
    steps:
      - checkout

      - restore_cache:
          keys:
            - cache-{{checksum "requirements.txt"}}\
              -{{.Environment.CACHE_VERSION}}

      - run:
          name: python module install
          command: |
            make setup_pip PIP_OPTION='--user'

      - save_cache:
          key: cache-{{ checksum "requirements.txt"}}\
              -{{.Environment.CACHE_VERSION}}
          paths:
            - ~/.local

      - run:
          name: Lint
          command: |
            make lint_python

      - run:
          name: Check Data
          command: |
            make check_data

workflows:
  version: 2
  build:
    jobs:
      - lint_with_node
      - file_check
